### ISSUE TITLE
Request For Revision To Include Notes On How To Use Multiple GitHub Accounts

### ISSUE THREAD

**Issue by SamuelBanya** [learn-co-curriculum/phase-0-macos-env-git-github#5]
### Canvas Link

https://learning.flatironschool.com/courses/5282/pages/mac-git-and-github-configuration?module_item_id=349367

### Concern

Though this is a pretty good explanation on how to setup Git for a single user on a global portion.

However, I wish there was a section on how to set it up for multiple GitHub accounts, ex: for a work based 'GitHub Enterprise' account as well as a personal 'GitHub' account.

**Comment by lizbur10** [comment]
Hi there,

Thank you for your feedback! We'll take this information into consideration in
upcoming releases of this curriculum.

As always, thanks for contributing! 💙
