### ISSUE TITLE
Just a clearification for students

### ISSUE THREAD

**Issue by dominickub** [learn-co-curriculum/phase-0-macos-env-git-github#7]
### Canvas Link

https://learning.flatironschool.com/courses/6150/pages/mac-git-and-github-configuration?module_item_id=482704

### Concern

In the "Action Item" section, I would recommend just stating to the students that there is no need to change the "Key Type" when you the page first opens. 

### Additional Context

![image](https://user-images.githubusercontent.com/89448197/196050505-8137afd6-88b8-4f03-92a1-9f3d51694518.png)

![image](https://user-images.githubusercontent.com/89448197/196050514-c821346e-664e-45da-805f-6ede567cbebe.png)

### Suggested Changes

I would just state it within line 8 in parenthesis (No need to change the key type)

**Comment by jlboba** [comment]
Hello, thank you for the suggestion! I've gone ahead and added clarification for this step. 
We appreciate your support! 💙
